name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel
          MYSQL_USER: sail
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      # Backend (Laravel)
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo_mysql
          coverage: none

      - name: Install Composer dependencies
        run: cd backend && composer install --prefer-dist --no-progress --no-suggest

      - name: Copy .env
        run: cp backend/.env.example backend/.env

      - name: Generate app key
        run: cd backend && php artisan key:generate

      - name: Run migrations
        run: cd backend && php artisan migrate --force

      - name: Run backend tests
        run: cd backend && php artisan test || true

      # Frontend (React)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install frontend dependencies
        run: cd client && npm install

      - name: Run frontend tests
        run: cd client && npm run test --if-present || true 